### ISSUE TITLE
Stylesheet Spacing Issue

### ISSUE THREAD

**Issue by ehmaddd** [Bestbynature/Aishatu-Gobir-Inaugural-Lecture#2]
https://github.com/Bestbynature/Aishatu-Gobir-Inaugural-Lecture/blob/600660de6f4bdbed73121edbd50b362f04061ab6/mystyles.css#L514

On line 514 in styles.css, there were several styling which only spanned a line for the whole adjustment, which may be confusing and misleading at times. So please if you fix it, it will be a better way.

**Comment by Bestbynature** [comment]
Thanks so much for your review. It's been looked into.
